apiVersion: v1
kind: Service
metadata:
  name: {{ include "offcon-service.name" . }}
  labels:
    {{- include "offcon-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "offcon-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
    {{- if gt (int .Values.ports.grpc) 0 }}
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
    {{- end }}
