-- =============================================================================
-- content — reconcile schema with ORM models
-- =============================================================================
-- The hand-written 0001 migration drifted from the SQLAlchemy models, so the
-- services 500'd on columns/tables that were declared but never created
-- (e.g. challenges.walkthrough_markdown). Generated by diffing Base.metadata
-- against the live database. New columns are nullable so this is safe to
-- apply to populated tables.
-- =============================================================================

ALTER TABLE content.categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE content.tags ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE content.tags ADD COLUMN IF NOT EXISTS color VARCHAR(7);
ALTER TABLE content.tags ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE content.challenges ADD COLUMN IF NOT EXISTS walkthrough_markdown TEXT;
ALTER TABLE content.machine_hints ADD COLUMN IF NOT EXISTS point_penalty INTEGER;
ALTER TABLE content.machine_hints ADD COLUMN IF NOT EXISTS flag_type VARCHAR(16);
ALTER TABLE content.machine_hints ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE content.path_enrollments ADD COLUMN IF NOT EXISTS progress_percent INTEGER;
ALTER TABLE content.path_enrollments ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE content.path_enrollments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE content.module_progress ADD COLUMN IF NOT EXISTS correct_answers INTEGER;
ALTER TABLE content.module_progress ADD COLUMN IF NOT EXISTS total_questions INTEGER;
ALTER TABLE content.module_progress ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE content.module_progress ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();
