-- =============================================================================
-- writeup — reconcile schema with ORM models
-- =============================================================================
-- The hand-written 0001 migration drifted from the SQLAlchemy models, so the
-- services 500'd on columns/tables that were declared but never created
-- (e.g. challenges.walkthrough_markdown). Generated by diffing Base.metadata
-- against the live database. New columns are nullable so this is safe to
-- apply to populated tables.
-- =============================================================================

ALTER TABLE writeup.bookmarks ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE writeup.comments ADD COLUMN IF NOT EXISTS content_html TEXT;
ALTER TABLE writeup.comments ADD COLUMN IF NOT EXISTS edit_count INTEGER;
ALTER TABLE writeup.comments ADD COLUMN IF NOT EXISTS downvote_count INTEGER;
ALTER TABLE writeup.comments ADD COLUMN IF NOT EXISTS score INTEGER;
ALTER TABLE writeup.comments ADD COLUMN IF NOT EXISTS edited_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE writeup.comments ADD COLUMN IF NOT EXISTS edited_by UUID;
ALTER TABLE writeup.comments ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE writeup.comments ADD COLUMN IF NOT EXISTS deleted_by UUID;
ALTER TABLE writeup.votes ADD COLUMN IF NOT EXISTS direction SMALLINT;
CREATE TABLE writeup.comment_votes (
	comment_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	direction SMALLINT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (comment_id, user_id), 
	CONSTRAINT uq_comment_vote UNIQUE (comment_id, user_id), 
	FOREIGN KEY(comment_id) REFERENCES writeup.comments (id) ON DELETE CASCADE
);
