-- =============================================================================
-- forum — reconcile schema with ORM models
-- =============================================================================
-- The hand-written 0001 migration drifted from the SQLAlchemy models, so the
-- services 500'd on columns/tables that were declared but never created
-- (e.g. challenges.walkthrough_markdown). Generated by diffing Base.metadata
-- against the live database. New columns are nullable so this is safe to
-- apply to populated tables.
-- =============================================================================

ALTER TABLE forum.categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE forum.reports ADD COLUMN IF NOT EXISTS target_type VARCHAR(16);
ALTER TABLE forum.reports ADD COLUMN IF NOT EXISTS target_id UUID;
ALTER TABLE forum.reports ADD COLUMN IF NOT EXISTS details TEXT;
ALTER TABLE forum.reports ADD COLUMN IF NOT EXISTS resolved_by UUID;
ALTER TABLE forum.reports ADD COLUMN IF NOT EXISTS resolution_note TEXT;
ALTER TABLE forum.reports ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE forum.user_reputation ADD COLUMN IF NOT EXISTS reputation INTEGER;
ALTER TABLE forum.user_reputation ADD COLUMN IF NOT EXISTS solutions_accepted INTEGER;
ALTER TABLE forum.user_reputation ADD COLUMN IF NOT EXISTS last_recomputed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE forum.thread_subscriptions ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN;
ALTER TABLE forum.thread_subscriptions ADD COLUMN IF NOT EXISTS in_app_notifications BOOLEAN;
ALTER TABLE forum.post_votes ADD COLUMN IF NOT EXISTS direction SMALLINT;
