-- Audit schema rollback
DROP TABLE IF EXISTS audit.security_events CASCADE;
DROP TABLE IF EXISTS audit.admin_actions_2026_06 CASCADE;
DROP TABLE IF EXISTS audit.admin_actions_2026_05 CASCADE;
DROP TABLE IF EXISTS audit.admin_actions CASCADE;
DROP TABLE IF EXISTS audit.log_2026_07 CASCADE;
DROP TABLE IF EXISTS audit.log_2026_06 CASCADE;
DROP TABLE IF EXISTS audit.log_2026_05 CASCADE;
DROP TABLE IF EXISTS audit.log CASCADE;
